# importing necessary libraries

import pandas as pd
import numpy as np

In [2]:
import pandas as pd
import numpy as np

# BASIC PYTHON

## 1.Split string

In [4]:
name="Hey! I am Sabarisshan G K"
s=name.split()
s

['Hey!', 'I', 'am', 'Sabarisshan', 'G', 'K']

## 2.Formated String

In [5]:
#We can format string by using .format() method 

name = "Sabarisshan G K"
department= "CSE"
print("Hi I am {name} from {department} department.".format(name=name,department=department))

Hi I am Sabarisshan G K from CSE department.


## 3. Extract hello from nested dictionary

In [6]:
nested_dictionary = {"k1":[1,2,3,
                   {"tricky":["oh","man","inception",
                              {"target":[1,2,3,"hello"]
                              }]}]
            }

print(nested_dictionary["k1"][3]["tricky"][3]["target"][3])

hello


# NUMPY

# # 4.Create an array of zeros

In [7]:
ar=np.zeros(5)
ar

array([0., 0., 0., 0., 0.])

## 5.Numpy array of all even integers from 10 to 60

In [9]:
arr=np.arange(10,61,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50, 52, 54, 56, 58, 60])

## 6. Create a 3x3 matrix

In [14]:
matrix= np.arange(1,10).reshape(3,3)
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## 7. Concatenate two arrays

In [15]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
merge=np.concatenate((arr1,arr2),axis=None)
merge

array([1, 2, 3, 4, 5, 6])

## 8.Create a dataframe with 3 rows and 2 columns

In [18]:
rand_num=np.random.randint(10,size=(3,2))
df=pd.DataFrame(rand_num,columns=["column 1", "column 2"])
df

column 1  column 2
0         6         6
1         6         4
2         9         6

In [3]:
pd_dict = {
    "col_1":[1,2,3],
    "col_2":[2,5,6]
          }
# Create dataframe by dictionary
df1 = pd.DataFrame(pd_dict)
df1

col_1  col_2
0      1      2
1      2      5
2      3      6

In [5]:
# Add dataframe by list 
name_list = ["Sachin Tendulkar",20],["Dwyane Johnson",20],["Jason Stathom",20],["Tom Halland",19]
df2 = pd.DataFrame(name_list,columns=["Name","Age"])
df2

Name  Age
0  Sachin Tendulkar   20
1    Dwyane Johnson   20
2     Jason Stathom   20
3       Tom Halland   19

## 9.Generate series of date from 1st jan 2023 - 10 th feb 2023

In [8]:
# dataframe Generator 
dfg = pd.DataFrame()

dfg["time"] = pd.date_range(start ="1/1/2023",end ="2/10/2023",freq ="24H")

dfg["year"] =dfg["time"].dt.year
dfg["month"] = dfg["time"].dt.month
dfg["day"] = dfg["time"].dt.day

In [9]:
dfg.head()

time  year  month  day
0 2023-01-01  2023      1    1
1 2023-01-02  2023      1    2
2 2023-01-03  2023      1    3
3 2023-01-04  2023      1    4
4 2023-01-05  2023      1    5

## 10. Create 2D list to dataframe

In [10]:
list_2d = [[1,"aaa",22],[2,"bbb",25],[3,"ccc",24]]
dl = pd.DataFrame(list_2d,columns=["col1","col2","col3"])
dl

col1 col2  col3
0     1  aaa    22
1     2  bbb    25
2     3  ccc    24